---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- name: Add remote user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker
    state: present

- name: Remove firewalld
  package: 
    name: firewalld
    state: absent

## RHEL bug workaround https://bugzilla.redhat.com/show_bug.cgi?id=1527565 
- name: Create rke user
  user:
    name: rke 
    shell: /bin/bash
    groups: docker

- name: Add ssh key to the rke user
  authorized_key:
    user: rke
    key: "{{ lookup('file', path_to_ssh_pub_key) }}"