---
# Purpose: Main task list import for role
# Last Updated: 2019.04.12
# Notes:

- include: add_authorized_key.yml

- include: docker_install_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include: docker_install_centos.yml
  when: ansible_os_family == 'RedHat'

- include: requirements.yml